### ISSUE TITLE
README.md should be changed! Please read!

### ISSUE THREAD

**Issue by lbrustad** [Crkza/senko-san#11]
Can you please fix the README.md file?

Please follow these rules when writing md files to host at GitHub:

- Keep in mind that 1 empty line of text will make sure you don't just write more at the previous line
- Writing code blocks:
  - Use \`\`\` at the line before the code starts (and of course after the last line too)
  - Or add 4 spaces before every single line in the code block
- Using alias urls at the bottom of the md file will make urls in the text look way more clean

Your usage of headers is good, but as you may have seen if you've ever coded markdown in GitHub's online editor, you get all the info about md coding at GitHub.

Now I just wish your project good luck! Maybe I may join the development if it's getting good ;)

**Comment by Crkza** [comment]
yea I'm really bad at Markdown. Will fix.

**Comment by Crkza** [comment]
Fixed the code! how does it look?
